variables:
  DEPLOY_DIR: /var/www/kostkarubika.net
  PROD_RELEASE_NAME: release-$CI_BUILD_ID
  STAGE_RELEASE_NAME: stage-$CI_BUILD_ID

generate production html:
  image: winglot/composer-alpine:1.1.2
  environment: production
  stage: build
  script: sh ./scripts/build-env prod
  artifacts:
    paths:
      - web/
  tags: [docker]
  only: [master]

deploy to production:
  environment: production
  stage: deploy
  script:
    - mv -v web $PROD_RELEASE_NAME
    - rsync -avWpz $PROD_RELEASE_NAME $DEPLOY_DIR/
    - ln -svfn $DEPLOY_DIR/$PROD_RELEASE_NAME $DEPLOY_DIR/current
  tags: [shell]
  only: [master]

generate staging html:
  image: winglot/composer-alpine:1.1.2
  environment: staging
  stage: build
  script: sh ./scripts/build-env stage
  artifacts:
    paths:
      - web/
  tags: [docker]
  except: [master]

deploy to staging:
  environment: staging
  stage: deploy
  script:
    - mv -v web $STAGE_RELEASE_NAME
    - rsync -avWpz $STAGE_RELEASE_NAME $DEPLOY_DIR/
    - ln -svfn $DEPLOY_DIR/$STAGE_RELEASE_NAME $DEPLOY_DIR/staging
  tags: [shell]
  except: [master]
