---
timezone: "Europe/Warsaw"
blacklist: ["timer.html.twig"]

title: "KostkaRubika.net - zacznij układać"
title_short: "KostkaRubika.net"

url: "http://kostkarubika.net"
assets: "//kostkarubika.net/assets"
layout: "_layout/article.html.twig"

mui_version: 0.9.1

ads: []

routes:
    history:            "/3x3x3/historia.html"
    positions:          "/3x3x3/pozycje_klockow.html"
    basics:             "/3x3x3/podstawy.html"
    c1_diy:             "/1x1x2/diy.html"
    c3_fridrich:        "/3x3x3/fridrich.html"
    c2_fridrich:        "/2x2x2/fridrich.html"
    c2_ortega:          "/2x2x2/ortega.html"
    c2_guimond:         "/2x2x2/guimond.html"
    c4_ukladanie:       "/4x4x4/ukladanie.html"
    c5_ukladanie:       "/5x5x5/ukladanie.html"
    pyraminx_ukladanie: "/pyraminx/ukladanie.html"
    square_ukladanie:   "/square/ukladanie.html"
    pages_cookies:      "/pages/cookies.html"
